### ISSUE TITLE
Object Reference Error

### ISSUE THREAD

**Issue by mtitdc** [congdongdotnet/ViewStateOptimizer#1]
After installing ViewState Optimizer from Nuget, when I tried to login in my asp.net web form application. It is throwing object reference not set to instance of object error.

Please help.

**Comment by ShirishPatel** [comment]
It works fine for me... Have you added the config details in the web.config ???

**Comment by ShirishPatel** [comment]
section name="viewStateOptimizer" type="ViewStateOptimizer
								.ViewStateOptimizerConfigurationSection"

make sure you write the code as below without the white spaces and enter like mentioned in the Readme:

section name="viewStateOptimizer" type="ViewStateOptimizer.ViewStateOptimizerConfigurationSection"

**Comment by 1001binary** [comment]
I believe that this issue has been already resolved.
